apiVersion: v2
name: sealed-secrets
version: 1.0.0
description: Sealed Secrets controller for encrypting secrets in Git
dependencies:
  - name: sealed-secrets
    version: "2.17.1"
    repository: "https://bitnami-labs.github.io/sealed-secrets"
